const TotalTimeType={
    SAVE_TOTAL_TIME:'SAVE_TOTAL_TIME',
    START_COUNTDOWN:'START_COUNTDOWN',
    PAUSE_COUNTDOWN:'PAUSE_COUNTDOWN',
    SET_COUNTDOWN_TRUE:'SET_COUNTDOWN_TRUE',
    UPDATE_COUNTDOWN:'UPDATE_COUNTDOWN',
    REMOVE_ALL_TIME:'REMOVE_ALL_TIME',
    UPDATE_LAST_RUN_TIME:'UPDATE_LAST_RUN_TIME',
}
export default TotalTimeType; 