const TaskType={
    ADD_TASK:'ADD_TASK',
    REMOVE_TASK:'REMOVE_TASK',
    PAUSE_TASK:'PAUSE_TASK',
    START_TASK:'START_TASK',
    COMPLETED_TASK:'COMPLETED_TASK',
    ADD_BREAK_TASK:'ADD_BREAK_TASK',
    REMOVE_ALL_TASK:'REMOVE_ALL_TASK',
    COMPLETE_ALL_TASK:'COMPLETE_ALL_TASK',
    ADD_REMAINDER:'ADD_REMAINDER',
    START_REMAINDER:'START_REMAINDER',
    
    
}
export default TaskType;